version: '3'

services:
  db:
    image: mongo:5
    container_name: uhealth-database
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: uhealth
    volumes:
      - ./mongo_data:/data/db